<?php

namespace cymapgt\core\application\authentication\UserCredential\services;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-05-18 at 14:28:58.
 */
class UserCredentialPasswordLoginServiceTest extends \PHPUnit\Framework\TestCase {

    /**
     * @var UserCredentialPasswordLoginService
     */
    protected $object;
    protected $password;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        //Make sure that UserCredentialPasswordLoginService is available to your auth plugin and create an instance
        $this->object   = new UserCredentialPasswordLoginService;
        
        /**
         * This is the password that is stored in DB hashed with \password_hash function. 
         * PHP 5.4 will be supported because of ircmaxell/password-compat package
         */
        $this->password = \password_hash('123456', \PASSWORD_DEFAULT);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers cymapgt\core\application\authentication\UserCredential\services\UserCredentialPasswordLoginService::initialize
     */
    public function testInitialize() {
        //username of authenticating user
        $this->object->setCurrentUserName('rhossis');
        
        //password that is stored in the DB
        $this->object->setCurrentPassword($this->password);
        
        //password input by the user in the login form / API
        $this->object->setPassword('123456');
        
        
        $this->assertEquals(null, $this->object->initialize());
    }
    
    /**
     * @covers cymapgt\core\application\authentication\UserCredential\services\UserCredentialPasswordLoginService::initialize
     * @expectedException \cymapgt\Exception\UserCredentialException
     * @expectedExceptionMessge The usercredential login service is not initialized with all parameters
     */
    public function testInitializeException() {
        //if you call initialize without setting the username, password and keyed in password, an exception should be thrown
        $this->object->initialize();
    }    

    /**
     * @covers cymapgt\core\application\authentication\UserCredential\services\UserCredentialPasswordLoginService::authenticate
     */
    public function testAuthenticate() {
        //test authentication where user has input the correct password
        $this->object->setCurrentUserName('rhossis');
        $this->object->setCurrentPassword($this->password);
        $this->object->setPassword('123456');
        
        //test authentication where user has input wrong password. We assume the user input 12345 instead of 123456
        $this->assertEquals(true, $this->object->authenticate());
        $this->object->setPassword('12345');
        $this->assertEquals(false, $this->object->authenticate());
    }
}
